"""initial schema

Revision ID: fb41ee0c358d
Revises: 
Create Date: 2026-03-29 20:21:32.653226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb41ee0c358d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_signals', sa.Column('run_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alert_signals_run_id'), 'alert_signals', ['run_id'], unique=False)
    op.create_foreign_key(None, 'alert_signals', 'strategy_runs', ['run_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alert_signals', type_='foreignkey')
    op.drop_index(op.f('ix_alert_signals_run_id'), table_name='alert_signals')
    op.drop_column('alert_signals', 'run_id')
    # ### end Alembic commands ###
